// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmzk7Jwx3Zi0RJf_PnJ42M17lbid4uBz4',
    appId: '1:1066682413909:web:2ebbfefd25dd6a630875dc',
    messagingSenderId: '1066682413909',
    projectId: 'applied-sciences-researhcenter',
    authDomain: 'applied-sciences-researhcenter.firebaseapp.com',
    storageBucket: 'applied-sciences-researhcenter.firebasestorage.app',
    measurementId: 'G-5F8QGYZWY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtooRZmrvWW-HX69zgzmTPWkFtOChggKQ',
    appId: '1:1066682413909:android:fbe7d0ee4e44d7110875dc',
    messagingSenderId: '1066682413909',
    projectId: 'applied-sciences-researhcenter',
    storageBucket: 'applied-sciences-researhcenter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhwMDPOS7ytZD5N2vZR5SpBNX1MxUsxkQ',
    appId: '1:1066682413909:ios:ba0232a0339a5f3d0875dc',
    messagingSenderId: '1066682413909',
    projectId: 'applied-sciences-researhcenter',
    storageBucket: 'applied-sciences-researhcenter.firebasestorage.app',
    iosBundleId: 'com.example.asrcFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhwMDPOS7ytZD5N2vZR5SpBNX1MxUsxkQ',
    appId: '1:1066682413909:ios:ba0232a0339a5f3d0875dc',
    messagingSenderId: '1066682413909',
    projectId: 'applied-sciences-researhcenter',
    storageBucket: 'applied-sciences-researhcenter.firebasestorage.app',
    iosBundleId: 'com.example.asrcFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmzk7Jwx3Zi0RJf_PnJ42M17lbid4uBz4',
    appId: '1:1066682413909:web:e94dfb4fc9ff24720875dc',
    messagingSenderId: '1066682413909',
    projectId: 'applied-sciences-researhcenter',
    authDomain: 'applied-sciences-researhcenter.firebaseapp.com',
    storageBucket: 'applied-sciences-researhcenter.firebasestorage.app',
    measurementId: 'G-PWRX6VSJTM',
  );
}
